component: "selenium-grid-4"

router:

  # -- Define router pod annotations
  annotations:

  repository: selenium/router
  tag: 4.0.0-rc-2-prerelease-20210908
  serviceType: "ClusterIP"
  loadBalancerSourceRanges: []

  # -- Configure router resource requests/limits
  resources:
    requests:
      # memory: "512Mi"
      # cpu: "0.5"
    limits:
      # memory: "1Gi"
      # cpu: "1"

  # -- Define router service port
  port: 4444
  # -- Define router service port name
  portName: web

  # -- Define router startup probe
  startupProbe:
    exec:
      command:
      - /bin/sh
      - -c
      - 'curl -sSL "http://localhost:4444/wd/hub/status" 2>&1 | jq -e ".value.ready"==true'
    periodSeconds: 10
    failureThreshold: 30

  # -- Define router readiness probe
  readinessProbe:
    exec:
      command:
      - /bin/sh
      - -c
      - 'curl -sSL "http://localhost:4444/wd/hub/status" 2>&1 | jq -e ".value.ready"==true'
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 1
    successThreshold: 1

  # -- Define router liveness probe
  livenessProbe:
    httpGet:
      path: /
      port: web
    initialDelaySeconds: 15
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1

  ingress:
    enabled: false
    # -- define custom annotations for ingress. Sample annotations are needed to use vnc with an nginx.org ingress
    annotations:
      # nginx.org/location-snippets: |
      #       proxy_set_header Upgrade $http_upgrade;
      #       proxy_set_header Connection upgrade;
      # nginx.org/proxy-connect-timeout: "3600"
      # nginx.org/proxy-read-timeout: "3600"
    ingressClassName: nginx
    # tls:
    # - hosts:
    #     - selenium-grid.kube.home
    #   secretName: tls-scret
    hosts:
      - selenium-grid.kube.home
    path: /

chrome:
  # -- Enable chrome node deployment
  enabled: true

  # -- Define chrome node pod annotations
  annotations:

  # -- Chrome node repository
  repository: "selenium/node-chrome"

  # -- Chrome node tag
  tag: "4.0.0-rc-2-prerelease-20210908"

  # -- Set chrome node replica count
  replicas: 1

  # Screen resolution, depth and dpi can be set via environment variables
  # https://github.com/SeleniumHQ/docker-selenium#setting-screen-resolution

  # -- (int) Chrome node screen width configuration
  screenWidth: 1920
  # -- (int) Chrome node screen heigth configuration
  screenHeight: 1080
  # -- (int) Chrome node screen depth configuration
  screenDepth:
  # -- (int) Chrome node screen dpi configuration
  screenDpi:

  # -- Configure chrome node resource requests/limits
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"

  # --  Configure chrome node volume mounts
  volumeMounts:
    - name: dshm
      mountPath: /dev/shm

  # --  Configure chrome node volume mounts
  volumes:
    - name: dshm
      emptyDir: { "medium": "Memory" }

  # -- Chrome node vnc port
  vncPort: 5900
  # -- Chrome node vnc target port
  vncTargetPort: 5900

  # -- VNC password can be disabled to enable vnc web view in grid
  vncNoPassword: true

  # -- Configure node grid url rewrite adress
  seNodeGridUrl: http://selenium-grid.kube.home

  # keda is able to scale chrome deployments according to length of grid queue size
  # https://keda.sh
  # https://keda.sh/docs/2.4/scalers/selenium-grid-scaler/
  autoscaler:
    enabled: false
    minReplicaCount: 0
    maxReplicaCount: 4

distributor:

  # -- Define distributor pod annotations
  annotations:

  repository: "selenium/distributor"
  tag: "4.0.0-rc-2-prerelease-20210908"

  # -- define distributor port
  distributorPort: 5553

eventBus:

  # -- Define event bus pod annotations
  annotations:

  repository: "selenium/event-bus"
  tag: "4.0.0-rc-2-prerelease-20210908"

  # -- define event bus publish port
  publishPort: 4442

  # -- define event bus subscribe port
  subscribePort: 4443

  # -- define the event bus port
  port: 5557

sessions:

  # -- Define sessions pod annotations
  annotations:

  repository: "selenium/sessions"
  tag: "4.0.0-rc-2-prerelease-20210908"

  # -- define the selenium sessions map port
  mapPort: 5556

sessionsQueue:

  # -- Define sessions-queue pod annotations
  annotations:

  repository: "selenium/session-queue"
  tag: "4.0.0-rc-2-prerelease-20210908"

  # -- define the selenium sessions queue port
  queuePort: 5559
