component: "selenium-grid-4"

router:
  repository: selenium/router
  tag: 4.0.0-rc-1-20210902
  serviceType: "ClusterIP"
  loadBalancerSourceRanges: []
  port: 4444
  servicePort: 4444

  port1: 4442
  port2: 4443

  ingress:
    enabled: true
    annotations:
    ingressClassName: nginx
    # tls:
    # - hosts:
    #     - selenium-grid.kube.home
    #   secretName: tls-scret
    hosts:
      - selenium-grid.kube.home
    path: /

chrome:
  # -- Enable chrome node deployment
  enabled: false

  # -- Chrome node repository
  repository: "selenium/node-chrome"

  # -- Chrome node tag
  tag: "4.0.0-rc-1-20210902"

  # -- Set chrome node replica count
  replicas: 1

  # Screen resolution, depth and dpi can be set via environment variables
  # https://github.com/SeleniumHQ/docker-selenium#setting-screen-resolution

  # -- (int) Chrome node screen width configuration
  screenWidth: 1920
  # -- (int) Chrome node screen heigth configuration
  screenHeight: 1080
  # -- (int) Chrome node screen depth configuration
  screenDepth:
  # -- (int) Chrome node screen dpi configuration
  screenDpi:

distributor:
  repository: "selenium/distributor"
  tag: "4.0.0-rc-1-20210902"
  port: 5553
  servicePort: 5553

eventBus:
  repository: "selenium/event-bus"
  tag: "4.0.0-rc-1-20210902"

sessions:
  repository: "selenium/sessions"
  tag: "4.0.0-rc-1-20210902"

sessionsQueue:
  repository: "selenium/session-queue"
  tag: "4.0.0-rc-1-20210902"
