component: "selenium-grid-4"

router:
  repository: selenium/router
  tag: 4.0.0-rc-1-20210902
  serviceType: "ClusterIP"
  loadBalancerSourceRanges: []

  # -- Configure router resource requests/limits
  resources:
    requests:
      # memory: "512Mi"
      # cpu: "0.5"
    limits:
      # memory: "1Gi"
      # cpu: "1"

  # -- Define router service port
  port: 4444
  # -- Define router service port name
  portName: web

  ingress:
    enabled: true
    # -- define custom annotations for ingress. Sample annotations are needed to use vnc with an nginx.org ingress
    annotations:
      # nginx.org/location-snippets: |
      #       proxy_set_header Upgrade $http_upgrade;
      #       proxy_set_header Connection upgrade;
      # nginx.org/proxy-connect-timeout: "3600"
      # nginx.org/proxy-read-timeout: "3600"
    ingressClassName: nginx
    # tls:
    # - hosts:
    #     - selenium-grid.kube.home
    #   secretName: tls-scret
    hosts:
      - selenium-grid.kube.home
    path: /

chrome:
  # -- Enable chrome node deployment
  enabled: true

  # -- Chrome node repository
  repository: "selenium/node-chrome"

  # -- Chrome node tag
  tag: "4.0.0-rc-1-20210902"

  # -- Set chrome node replica count
  replicas: 1

  # Screen resolution, depth and dpi can be set via environment variables
  # https://github.com/SeleniumHQ/docker-selenium#setting-screen-resolution

  # -- (int) Chrome node screen width configuration
  screenWidth: 1920
  # -- (int) Chrome node screen heigth configuration
  screenHeight: 1080
  # -- (int) Chrome node screen depth configuration
  screenDepth:
  # -- (int) Chrome node screen dpi configuration
  screenDpi:

  # -- Configure chrome node resource requests/limits
  resources:
    requests:
      memory: "1Gi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "1"

  # -- Chrome node vnc port
  vncPort: 5900
  # -- Chrome node vnc target port
  vncTargetPort: 5900

  # -- VNC password can be disabled to enable vnc web view in grid
  vncNoPassword: true

  # -- Configure node grid url rewrite adress
  seNodeGridUrl: http://selenium-grid.kube.home

  # keda is able to scale chrome deployments according to length of grid queue size
  # https://keda.sh
  # https://keda.sh/docs/2.4/scalers/selenium-grid-scaler/
  autoscaler:
    enabled: false
    minReplicaCount: 0
    maxReplicaCount: 4

distributor:
  repository: "selenium/distributor"
  tag: "4.0.0-rc-1-20210902"

  # -- define distributor port
  distributorPort: 5553

eventBus:
  repository: "selenium/event-bus"
  tag: "4.0.0-rc-1-20210902"

  # -- define event bus publish port
  publishPort: 4442

  # -- define event bus subscribe port
  subscribePort: 4443

  # -- define the event bus port
  port: 5557

sessions:
  repository: "selenium/sessions"
  tag: "4.0.0-rc-1-20210902"

  # -- define the selenium sessions map port
  mapPort: 5556

sessionsQueue:
  repository: "selenium/session-queue"
  tag: "4.0.0-rc-1-20210902"

  # -- define the selenium sessions queue port
  queuePort: 5559
