component: "selenium-grid-4"

router:
  repository: selenium/router
  tag: 4.0.0-rc-1-20210902
  serviceType: "ClusterIP"
  loadBalancerSourceRanges: []
  port: 4444
  servicePort: 4444

  port1: 4442
  port2: 4443

chrome:
  enabled: false
  repository: "selenium/node-chrome"
  tag: "4.0.0-rc-1-20210902"
  replicas: 1

distributor:
  repository: "selenium/distributor"
  tag: "4.0.0-rc-1-20210902"
  port: 5553
  servicePort: 5553

eventBus:
  repository: "selenium/event-bus"
  tag: "4.0.0-rc-1-20210902"

sessions:
  repository: "selenium/sessions"
  tag: "4.0.0-rc-1-20210902"

sessionsQueue:
  repository: "selenium/session-queue"
  tag: "4.0.0-rc-1-20210902"
