{{- if .Values.chrome.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "selenium.chrome.fullname" . }}
  labels:
    name: {{ template "selenium.chrome.fullname" . }}
    component: {{ .Values.component }}
spec:
  selector:
    app: {{ template "selenium.chrome.fullname" . }}
  ports:
      # use speaking portname here
    - name: vncport
      protocol: TCP
      # Service uses ports different and not defined in chrome-deployment.yaml - better define in values.yaml as default
      port: {{ .Values.chrome.vncPort }}
      targetPort: {{ .Values.chrome.vncTargetPort }}
{{- end }}
