{{- if .Values.chrome.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "selenium.chrome.fullname" . }}
  labels:
    app: {{ template "selenium.chrome.fullname" . }}
    name: {{ template "selenium.chrome.fullname" . }}
    component: {{ .Values.component }}
spec:
  replicas: {{ .Values.chrome.replicas }}
  selector:
    matchLabels:
      app: {{ template "selenium.chrome.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "selenium.chrome.fullname" . }}
        name: {{ template "selenium.chrome.fullname" . }}
        component: {{ .Values.component }}
    spec:
      containers:
        - name: {{ template "selenium.chrome.fullname" . }}
          image: "{{ .Values.chrome.repository }}:{{ .Values.chrome.tag }}"
          env:
            - name: SE_EVENT_BUS_HOST
              value: {{ include "selenium.event-bus.fullname" . | quote }}
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 5553
              protocol: TCP
{{- end }}
