{{- if .Values.chrome.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "selenium.chrome.fullname" . }}
  labels:
    app: {{ template "selenium.chrome.fullname" . }}
    name: {{ template "selenium.chrome.fullname" . }}
    component: {{ .Values.component }}
spec:
  replicas: {{ .Values.chrome.replicas }}
  selector:
    matchLabels:
      app: {{ template "selenium.chrome.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "selenium.chrome.fullname" . }}
        name: {{ template "selenium.chrome.fullname" . }}
        component: {{ .Values.component }}
    spec:
      containers:
        - name: {{ template "selenium.chrome.fullname" . }}
          image: "{{ .Values.chrome.repository }}:{{ .Values.chrome.tag }}"
          env:
            - name: SE_EVENT_BUS_HOST
              value: {{ include "selenium.event-bus.fullname" . | quote }}
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: {{ .Values.eventBus.publishPort | quote }}
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: {{ .Values.eventBus.subscribePort | quote }}
            {{- if .Values.chrome.screenWidth }}
            - name: SCREEN_WIDTH
              value: {{ .Values.chrome.screenWidth | quote }}
            {{- end }}
            {{- if .Values.chrome.screenHeight }}
            - name: SCREEN_HEIGHT
              value: {{ .Values.chrome.screenHeight | quote }}
            {{- end }}
            {{- if .Values.chrome.screenDepth }}
            - name: SCREEN_DEPTH
              value: {{ .Values.chrome.screenDepth | quote }}
            {{- end }}
            {{- if .Values.chrome.screenDpi }}
            - name: SCREEN_DPI
              value: {{ .Values.chrome.screenDpi | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.distributor.distributorPort }}
              protocol: TCP
{{- end }}
