apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "selenium.distributor.fullname" . }}
  labels:
    app: {{ template "selenium.distributor.fullname" . }}
    name: {{ template "selenium.distributor.fullname" . }}
    component: {{ .Values.component }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "selenium.distributor.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "selenium.distributor.fullname" . }}
        name: {{ template "selenium.distributor.fullname" . }}
        component: {{ .Values.component }}
      {{- with .Values.distributor.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ template "selenium.distributor.fullname" . }}
          image: "{{ .Values.distributor.repository }}:{{ .Values.distributor.tag }}"
          env:
            - name: SE_EVENT_BUS_HOST
              value: {{ include "selenium.event-bus.fullname" . | quote }}
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: {{ .Values.eventBus.publishPort | quote }}
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: {{ .Values.eventBus.subscribePort | quote }}
            - name: SE_SESSIONS_MAP_HOST
              value: {{ include "selenium.sessions.fullname" . | quote }}
            - name: SE_SESSIONS_MAP_PORT
              value: {{ .Values.sessions.mapPort | quote }}
            - name: SE_SESSION_QUEUE_HOST
              value: {{ include "selenium.sessions-queue.fullname" . | quote }}
            - name: SE_SESSION_QUEUE_PORT
              value: {{ .Values.sessionsQueue.queuePort | quote }}
          ports:
            - containerPort: {{ .Values.distributor.distributorPort }}
              protocol: TCP
