apiVersion: v1
kind: Service
metadata:
  name: {{ template "selenium.distributor.fullname" . }}
  labels:
    name: {{ template "selenium.distributor.fullname" . }}
    component: {{ .Values.component }}
spec:
  selector:
    app: {{ template "selenium.distributor.fullname" . }}
  ports:
    - name: distributorport
      protocol: TCP
      port: {{ .Values.distributor.distributorPort }}
      targetPort: {{ .Values.distributor.distributorPort }}
