apiVersion: v1
kind: Service
metadata:
  name: {{ template "selenium.event-bus.fullname" . }}
  labels:
    name: {{ template "selenium.event-bus.fullname" . }}
    component: {{ .Values.component }}
spec:
  selector:
    app: {{ template "selenium.event-bus.fullname" . }}
  ports:
    # use named ports and port numbers from values.yaml
    - name: port1
      protocol: TCP
      port: 4442
      targetPort: 4442
    - name: port2
      protocol: TCP
      port: 4443
      targetPort: 4443
    - name: port3
      protocol: TCP
      port: 5557
      targetPort: 5557
