apiVersion: v1
kind: Service
metadata:
  name: {{ template "selenium.event-bus.fullname" . }}
  labels:
    name: {{ template "selenium.event-bus.fullname" . }}
    component: {{ .Values.component }}
spec:
  selector:
    app: {{ template "selenium.event-bus.fullname" . }}
  ports:
    - name: publishport
      protocol: TCP
      port: {{ .Values.eventBus.publishPort }}
      targetPort: {{ .Values.eventBus.publishPort }}
    - name: subscribeport
      protocol: TCP
      port: {{ .Values.eventBus.subscribePort }}
      targetPort: {{ .Values.eventBus.subscribePort }}
    - name: port
      protocol: TCP
      port: {{ .Values.eventBus.port }}
      targetPort: {{ .Values.eventBus.port }}
