{{- if .Values.router.ingress.enabled -}}
{{- $ingressPath := .Values.router.ingress.path -}}
{{- $routerFullName := include "selenium.router.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $routerFullName }}
  {{- with .Values.router.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.router.ingress.ingressClassName }}
  {{- if .Values.router.ingress.tls }}
  tls:
    {{- range .Values.router.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.router.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ $routerFullName }}
                port:
                  number: 4444
  {{- end }}
{{- end }}
