apiVersion: v1
kind: Service
metadata:
  name: {{ template "selenium.router.fullname" . }}
  labels:
    name: {{ template "selenium.router.fullname" . }}
    component: {{ .Values.component }}
spec:
  type: {{ .Values.router.serviceType | quote }}
  {{- if .Values.router.serviceLoadBalancerIP }}
  loadBalancerIP: {{ .Values.router.serviceLoadBalancerIP | quote }}
  {{- end }}
  selector:
    app: {{ template "selenium.router.fullname" . }}
  ports:
    - name: {{ .Values.router.portName }}
      protocol: TCP
      port: {{ .Values.router.port }}
      targetPort: {{ .Values.router.port }}
