apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "selenium.router.fullname" . }}
  labels:
    app: {{ template "selenium.router.fullname" . }}
    name: {{ template "selenium.router.fullname" . }}
    component: {{ .Values.component }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "selenium.router.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "selenium.router.fullname" . }}
        name: {{ template "selenium.router.fullname" . }}
        component: {{ .Values.component }}
      {{- with .Values.router.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ template "selenium.router.fullname" . }}
          image: "{{ .Values.router.repository }}:{{ .Values.router.tag }}"
          env:
            - name: SE_DISTRIBUTOR_HOST
              value: {{ include "selenium.distributor.fullname" . | quote }}
            - name: SE_DISTRIBUTOR_PORT
              value: {{ .Values.distributor.distributorPort | quote }}
            - name: SE_SESSIONS_MAP_HOST
              value: {{ include "selenium.sessions.fullname" . | quote }}
            - name: SE_SESSIONS_MAP_PORT
              value: {{ .Values.sessions.mapPort | quote }}
            - name: SE_SESSION_QUEUE_HOST
              value: {{ include "selenium.sessions-queue.fullname" . | quote }}
            - name: SE_SESSION_QUEUE_PORT
              value: {{ .Values.sessionsQueue.queuePort | quote }}
          ports:
            - containerPort: {{ .Values.router.port }}
              protocol: TCP
          resources: {{ toYaml .Values.router.resources | nindent 12 }}
          {{- with .Values.router.startupProbe }}
          startupProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.router.readinessProbe }}
          readinessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.router.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
