apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "selenium.sessions-queue.fullname" . }}
  labels:
    app: {{ template "selenium.sessions-queue.fullname" . }}
    name: {{ template "selenium.sessions-queue.fullname" . }}
    component: {{ .Values.component }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "selenium.sessions-queue.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "selenium.sessions-queue.fullname" . }}
        name: {{ template "selenium.sessions-queue.fullname" . }}
        component: {{ .Values.component }}
    spec:
      containers:
        - name: {{ template "selenium.sessions-queue.fullname" . }}
          image: "{{ .Values.sessionsQueue.repository }}:{{ .Values.sessionsQueue.tag }}"
          env:
            - name: SE_EVENT_BUS_HOST
              value: {{ include "selenium.event-bus.fullname" . | quote }}
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
              # use port value from values.yaml
            - containerPort: 5556
              protocol: TCP
