apiVersion: v1
kind: Service
metadata:
  name: {{ template "selenium.sessions-queue.fullname" . }}
  labels:
    name: {{ template "selenium.sessions-queue.fullname" . }}
    component: {{ .Values.component }}
spec:
  selector:
    app: {{ template "selenium.sessions-queue.fullname" . }}
  ports:
    - name: port1
      protocol: TCP
      port: 5559
      targetPort: 5559
