apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "selenium.sessions-queue.fullname" . }}
  labels:
    app: {{ template "selenium.sessions-queue.fullname" . }}
    name: {{ template "selenium.sessions-queue.fullname" . }}
    component: {{ .Values.component }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "selenium.sessions-queue.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "selenium.sessions-queue.fullname" . }}
        name: {{ template "selenium.sessions-queue.fullname" . }}
        component: {{ .Values.component }}
      {{- with .Values.sessionsQueue.annotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ template "selenium.sessions-queue.fullname" . }}
          image: "{{ .Values.sessionsQueue.repository }}:{{ .Values.sessionsQueue.tag }}"
          env:
            - name: JAVA_OPTS
              value: {{ .Values.sessionsQueue.javaOpts | default "" | quote }}
            - name: SE_EVENT_BUS_HOST
              value: {{ include "selenium.event-bus.fullname" . | quote }}
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: {{ .Values.eventBus.publishPort | quote }}
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: {{ .Values.eventBus.subscribePort | quote }}
            {{- if .Values.sessionsQueue.requestTimeout }}
            - name: SE_SESSION_REQUEST_TIMEOUT
              value: {{ .Values.sessionsQueue.requestTimeout | quote }}
            {{- end }}
            {{- if .Values.sessionsQueue.retryInterval }}
            - name: SE_SESSION_RETRY_INTERVAL
              value: {{ .Values.sessionsQueue.retryInterval | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.sessions.mapPort }}
              protocol: TCP
