apiVersion: v1
kind: Service
metadata:
  name: {{ template "selenium.sessions.fullname" . }}
  labels:
    name: {{ template "selenium.sessions.fullname" . }}
    component: {{ .Values.component }}
spec:
  selector:
    app: {{ template "selenium.sessions.fullname" . }}
  ports:
    - name: port1
      protocol: TCP
      port: {{ .Values.sessions.mapPort }}
      targetPort: {{ .Values.sessions.mapPort }}
